Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-20.04"
  config.vm.network "forwarded_port", guest: 80, host: 8086
  ####### Provision #######
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
    # ansible.verbose = true
    ansible.extra_vars = {
      artifact: ENV.fetch("ARTIFACT", ""),
      commit: ENV.fetch("ARTIFACT_COMMIT", ""),
      ansible_python_interpreter: "/usr/bin/python3",
      home_dir: "/home/vagrant",
    }
  end
end
